import { createBenchSession } from "../../agents/session.js";
import type { WorkflowContext, LogEvent } from "../types.js";
import { mkdirSync } from "node:fs";
import { join } from "node:path";

export async function runUnitTestsToCode(ctx: WorkflowContext): Promise<void> {
  const metadataDir = join(ctx.cwd, ".ownbench", "metadata");
  mkdirSync(metadataDir, { recursive: true });

  const { session, dispose } = await createBenchSession(ctx.cwd);

  let nextId = 0;
  const emit = (event: LogEvent) => ctx.onEvent?.(event);

  session.subscribe((event) => {
    if (event.type === "tool_execution_start") {
      emit({
        type: "tool_start",
        id: nextId++,
        toolName: event.toolName,
        args: event.args as Record<string, unknown>,
      });
    } else if (event.type === "tool_execution_end") {
      emit({
        type: "tool_end",
        id: nextId++,
        toolName: event.toolName,
        result: event.result,
        isError: event.isError,
      });
    } else if (event.type === "tool_execution_update") {
      emit({
        type: "tool_update",
        id: nextId++,
        partialResult: event.partialResult,
      });
    } else if (
      event.type === "message_update" &&
      event.assistantMessageEvent.type === "thinking_delta"
    ) {
      emit({
        type: "thinking",
        id: nextId++,
        delta: event.assistantMessageEvent.delta,
      });
    } else if (
      event.type === "message_update" &&
      event.assistantMessageEvent.type === "text_delta"
    ) {
      emit({
        type: "text",
        id: nextId++,
        delta: event.assistantMessageEvent.delta,
      });
    }
  });

  const prompt = `You are OwnBench, a codebase analysis agent. Your task is to scan the project at ${
    ctx.cwd
  } and produce a metadata report.

## Task
Create a markdown file listing all **functional source code files** in this project, sorted descending by lines of code.

## Output location
Use the \`write_ownbench\` tool to write the file to: \`metadata/functional_files.md\`

## What is a "functional code file"?
- Source code files containing application logic: .ts, .js, .tsx, .jsx, .py, .java, .go, .rs, .rb, .php, .c, .cpp, .h, .cs, .swift, .kt, .scala, .ex, .exs, .clj, .hs, .elm, .dart, .vue, .svelte
- EXCLUDE the following:
  * Test files (paths containing test/, spec/, __tests__/, or files named *.test.*, *.spec.*)
  * Config/setup files (package.json, tsconfig*, vite.config.*, *.config.*, .eslintrc, .prettierrc, tailwind.config.*, postcss.config.*, docker-compose.yml, Dockerfile, Makefile)
  * Markdown, JSON, YAML, TOML, XML, HTML, CSS, SVG files
  * Build outputs (dist/, build/, out/, .next/, node_modules/)
  * Generated/protobuf/graphql schema files (*.graphql, *_pb.*, *-pb.*)
  * Type declaration files (*.d.ts) that are not source logic
  * dotfiles and lock files (.gitignore, .env*, yarn.lock, pnpm-lock.yaml, etc.)
  * CI/CD files (.github/workflows/, .gitlab-ci.yml, Jenkinsfile)

## Steps
1. Use \`find\` with \`-not -path '*/node_modules/*'\` and similar exclusions to list candidate files
2. Use \`wc -l\` to count lines in each candidate file (batch them efficiently with xargs)
3. For each file, briefly read the first few lines or filename to confirm it's functional code (not a test or config)
4. Compile the final list sorted by line count descending
5. Use \`write_ownbench\` to write \`metadata/functional_files.md\`

## Output format

\`\`\`markdown
# Functional Code Files

> Generated by OwnBench
> Project: ${ctx.cwd}

| # | File | Lines | Description |
|---|------|-------|-------------|
| 1 | \`src/submit.ts\` | 892 | Main form submission handler |
| 2 | \`src/auth/login.ts\` | 534 | Authentication logic |
| ... | ... | ... | ... |
\`\`\`

- Paths relative to project root (${ctx.cwd})
- Description: brief 3-6 word summary of the file's purpose
- Sort descending by Lines column

## Important rules
- Do NOT edit or modify any source files. This is a read-only analysis.
- Only write output via the \`write_ownbench\` tool — never use \`write\` or \`edit\` on project files.
- You do NOT have access to the \`write\` or \`edit\` built-in tools — they are disabled. Use \`write_ownbench\` instead.
- Be thorough: scan the ENTIRE codebase, not just top-level directories.
- Do not skip any source directory that contains functional code.
- The output directory \`.ownbench/metadata/\` already exists.`;

  try {
    await session.prompt(prompt);
  } finally {
    dispose();
  }
}
